// =============================================================================
// home-control-services — main entry point
//
// Polls all 5 EISYs on a configurable interval, maintains an in-memory state
// cache, and serves the state contract:
//
//   GET  /state    — full snapshot (JSON)
//   GET  /stream   — SSE patch stream
//   POST /command  — device command (202 + optimistic patch)
//
// State ids are namespaced by EISY index:
//   Device:   eisy{N}/{address}   e.g. "eisy0/14 35 EB 1"
//   Variable: eisy{N}/var/{id}    e.g. "eisy2/var/42"
//
// The Next.js proxy (next-app/src/lib/state-service.ts) translates between
// these state ids and the WP databaseIds used by the UI.
// =============================================================================

import express, { type Request, type Response } from 'express';
import cors from 'cors';
import { createReadStream } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PORT, EISY_URLS, POLL_MS, NEXT_APP_URL, HCA_INTERNAL_KEY } from './config.js';
import { getNodeStatus, getVariables, sendNodeCommand, setVariable } from './eisy-client.js';
import { applyPatch, getSnapshot, subscribe } from './state-store.js';
import { nodeToState, varToState, patchToNodeCommand, type DevicesMap } from './state-mapper.js';
import { readFileSync } from 'node:fs';

// ---------------------------------------------------------------------------
// Load devices.json (generated by scripts/export-devices.ts)
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
const devicesPath = join(__dirname, '..', 'devices.json');

let devices: DevicesMap = {};
try {
  devices = JSON.parse(readFileSync(devicesPath, 'utf8')) as DevicesMap;
  console.log(`[devices] loaded ${Object.keys(devices).length} entries`);
} catch {
  console.warn('[devices] devices.json not found or invalid — run: npm run export-devices');
}

// ---------------------------------------------------------------------------
// Push notification helper
// ---------------------------------------------------------------------------

async function sendPushAlert(body: string): Promise<void> {
  if (!HCA_INTERNAL_KEY || !NEXT_APP_URL) return;
  try {
    await fetch(`${NEXT_APP_URL}/api/push/notify`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-HCA-Internal-Key': HCA_INTERNAL_KEY,
      },
      body: JSON.stringify({ title: 'Home Control', body, url: '/' }),
      signal: AbortSignal.timeout(5_000),
    });
  } catch (err) {
    console.warn('[push] notify failed:', err instanceof Error ? err.message : err);
  }
}

// ---------------------------------------------------------------------------
// Polling loop
// ---------------------------------------------------------------------------

async function pollEisy(eisyIdx: number): Promise<void> {
  const baseUrl = EISY_URLS[eisyIdx];

  // Nodes (Insteon devices)
  const nodeStatus = await getNodeStatus(baseUrl);
  for (const [address, props] of nodeStatus) {
    const stateId = `eisy${eisyIdx}/${address}`;
    const entry = devices[stateId];
    if (!entry) continue;
    const state = nodeToState(entry.class, props);
    // Leak sensors: node 1 = Dry, node 2 = Wet, node 4 = Heartbeat.
    // Read wet state from node 2 (overriding the dry-node value).
    // Battery: absence of heartbeat (node 4 ST === 0) means low battery.
    // State is emitted under the node-1 key so the WP controlStateIds mapping stays valid.
    if (entry.class === 'leak-sensor' && address.endsWith(' 1')) {
      const wetAddr  = address.slice(0, -1) + '2';
      const battAddr = address.slice(0, -1) + '4';
      const wetProps  = nodeStatus.get(wetAddr);
      (state as Record<string, unknown>).wet = (wetProps?.get('ST') ?? 0) > 0;
      if (devices[`eisy${eisyIdx}/${battAddr}`]?.class === 'leak-battery') {
        const battProps = nodeStatus.get(battAddr);
        const isLow = (battProps?.get('ST') ?? 0) === 0; // no heartbeat = low battery
        (state as Record<string, unknown>).lowBattery = isLow;
        if (isLow) {
          const prevLow = !!(getSnapshot()[stateId] as { lowBattery?: boolean } | undefined)?.lowBattery;
          if (!prevLow) void sendPushAlert(`A water leak sensor is reporting low battery. Open the app to see which one.`);
        }
      }
    }
    // Motion sensors: node 1 = motion, node 2 = battery.
    if (entry.class === 'motion-sensor' && address.endsWith(' 1')) {
      const battAddr = address.slice(0, -1) + '2';
      if (devices[`eisy${eisyIdx}/${battAddr}`]?.class === 'motion-battery') {
        const battProps = nodeStatus.get(battAddr);
        const isLow = (battProps?.get('ST') ?? 0) > 0;
        (state as Record<string, unknown>).lowBattery = isLow;
        if (isLow) {
          const prevLow = !!(getSnapshot()[stateId] as { lowBattery?: boolean } | undefined)?.lowBattery;
          if (!prevLow) void sendPushAlert(`A motion sensor is reporting low battery. Open the app to see which one.`);
        }
      }
    }
    applyPatch(stateId, state);
  }

  // Integer variables (type 1) + state variables (type 2)
  for (const varType of [1, 2] as const) {
    const vars = await getVariables(baseUrl, varType);
    for (const [varId, val] of vars) {
      const stateId = `eisy${eisyIdx}/var/${varId}`;
      const entry = devices[stateId];
      if (!entry) continue;
      // Only apply if this entry's stored varType matches (avoids type-1/type-2 collisions)
      if (entry.varType !== undefined && entry.varType !== varType) continue;
      applyPatch(stateId, varToState(entry.class, val));
    }
  }
}

async function pollAll(): Promise<void> {
  await Promise.allSettled(
    EISY_URLS.map((_, idx) =>
      pollEisy(idx).catch((err: unknown) =>
        console.warn(`[eisy${idx}] poll error:`, err instanceof Error ? err.message : err),
      ),
    ),
  );
}

// Non-overlapping poll loop — waits for each poll to finish before
// scheduling the next. Prevents connection exhaustion when polls are
// slower than POLL_MS (e.g. under network hiccups or high EISY load).
(async function pollLoop() {
  while (true) {
    const t0 = Date.now();
    await pollAll();
    const wait = Math.max(0, POLL_MS - (Date.now() - t0));
    if (wait > 0) await new Promise<void>(r => setTimeout(r, wait));
  }
})().catch(console.error);

// ---------------------------------------------------------------------------
// Express app
// ---------------------------------------------------------------------------

const app = express();
app.use(cors());
app.use(express.json());

// GET /state — full snapshot
app.get('/state', (_req: Request, res: Response) => {
  res.json(getSnapshot());
});

// GET /stream — SSE
const SSE_HEADERS = {
  'Content-Type':      'text/event-stream',
  'Cache-Control':     'no-cache, no-transform',
  'Connection':        'keep-alive',
  'X-Accel-Buffering': 'no',
} as const;

app.get('/stream', (req: Request, res: Response) => {
  res.writeHead(200, SSE_HEADERS);
  res.write(': connected\n\n');

  const unsub = subscribe((chunk) => {
    res.write(chunk);
    (res as unknown as { flush?: () => void }).flush?.();
  });

  const heartbeat = setInterval(() => {
    try { res.write(': heartbeat\n\n'); }
    catch { clearInterval(heartbeat); }
  }, 30_000);

  req.on('close', () => {
    unsub();
    clearInterval(heartbeat);
  });
});

// POST /command
interface CommandBody {
  target: string;
  patch?: Record<string, unknown>;
  action?: string;
}

app.post('/command', (req: Request, res: Response) => {
  const body = req.body as CommandBody;
  if (!body?.target) {
    res.status(400).json({ error: 'Missing target' });
    return;
  }

  const entry = devices[body.target];
  if (!entry) {
    // Unknown target — log and return 404.
    // (Scenes and non-device targets pass through without a devices.json entry.)
    console.warn(`[command] unknown target: ${body.target}`);
    res.status(404).json({ error: `Unknown target: ${body.target}` });
    return;
  }

  // Respond 202 immediately (optimistic model — stream confirms)
  res.status(202).end();

  // Apply patch optimistically to the local state so the SSE stream fans it out
  if (body.patch) applyPatch(body.target, body.patch);

  // Forward to EISY asynchronously
  const baseUrl = EISY_URLS[entry.eisyIdx];
  void (async () => {
    try {
      if (entry.type === 'device' && entry.address) {
        const nodeCmd = patchToNodeCommand(entry.class, body.patch ?? {}, body.action);
        if (nodeCmd) {
          console.log(`[command] node ${body.target} → ${baseUrl} ${nodeCmd.cmd}${nodeCmd.value !== undefined ? '/' + nodeCmd.value : ''}`);
          await sendNodeCommand(baseUrl, entry.address, nodeCmd.cmd, nodeCmd.value);
        }
      } else if (entry.type === 'variable' && entry.varType != null && entry.varId != null) {
        // Accept any boolean state field (on/open/locked → 1/0) or an explicit
        // numeric value. Matches the per-class shapes varToState emits, so e.g.
        // a contact-sensor door sends { open } and a flag sends { on }.
        const boolField = body.patch?.on ?? body.patch?.open ?? body.patch?.locked;
        const val = typeof boolField === 'boolean'
          ? (boolField ? 1 : 0)
          : typeof body.patch?.value === 'number'
            ? Math.round(body.patch.value as number)
            : 0;
        console.log(`[command] var ${body.target} → ${baseUrl} vars/set/${entry.varType}/${entry.varId}/${val}`);
        await setVariable(baseUrl, entry.varType, entry.varId, val);
        console.log(`[command] var ${body.target} ✓`);
      }
    } catch (err) {
      console.warn(
        `[command] ${body.target} FAILED:`,
        err instanceof Error ? err.message : err,
      );
    }
  })();
});

app.listen(PORT, () => {
  console.log(`home-control-service listening on :${PORT}`);
  console.log(`  /state   GET  full snapshot`);
  console.log(`  /stream  GET  SSE patch stream`);
  console.log(`  /command POST device commands`);
});
