// =============================================================================
// home-control-services — main entry point
//
// Polls all 5 EISYs on a configurable interval, maintains an in-memory state
// cache, and serves the state contract:
//
//   GET  /state    — full snapshot (JSON)
//   GET  /stream   — SSE patch stream
//   POST /command  — device command (202 + optimistic patch)
//
// State ids are namespaced by EISY index:
//   Device:   eisy{N}/{address}   e.g. "eisy0/14 35 EB 1"
//   Variable: eisy{N}/var/{id}    e.g. "eisy2/var/42"
//
// The Next.js proxy (next-app/src/lib/state-service.ts) translates between
// these state ids and the WP databaseIds used by the UI.
// =============================================================================

import express, { type Request, type Response } from 'express';
import cors from 'cors';
import { createReadStream } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PORT, EISY_URLS, POLL_MS, NEXT_APP_URL, HCA_INTERNAL_KEY } from './config.js';
import { getNodeStatus, getVariables, sendNodeCommand, setVariable } from './eisy-client.js';
import { applyPatch, getSnapshot, subscribe } from './state-store.js';
import { nodeToState, varToState, patchToNodeCommand, type DevicesMap } from './state-mapper.js';
import { readFileSync } from 'node:fs';

// ---------------------------------------------------------------------------
// Load devices.json (generated by scripts/export-devices.ts)
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
const devicesPath = join(__dirname, '..', 'devices.json');

let devices: DevicesMap = {};
try {
  devices = JSON.parse(readFileSync(devicesPath, 'utf8')) as DevicesMap;
  console.log(`[devices] loaded ${Object.keys(devices).length} entries`);
} catch {
  console.warn('[devices] devices.json not found or invalid — run: npm run export-devices');
}

// ---------------------------------------------------------------------------
// Push notification helper
// ---------------------------------------------------------------------------

/**
 * Fire a push notification.
 *
 * Copy rule: `title` and `body` must read correctly in two places — as a system
 * banner AND as a row in the app's notification inbox. Never write "open the
 * app to see…"; the reader may already be in the app. Pass a `url` with
 * ?screen=<id> instead, which makes both the banner and the inbox row tappable.
 */
interface PushAlertOpts {
  alertKey?: string;
  url?: string;
  category?: string;
  /** High-urgency delivery and a banner that stays until the user acts on it. */
  urgent?: boolean;
  /** Repeat interval while the condition persists. Defaults to the app's 24 h. */
  resendMinutes?: number;
  /** State id of the device. The app substitutes `{device}` in the title/body
   *  with its config-plane name — names are WP's job, not this service's. */
  deviceId?: string;
}

/** Returns false when the app couldn't be reached, so the caller can retry.
 *  Recording a send that never left would silence the alert for 24 h. */
async function sendPushAlert(
  title: string,
  body: string,
  opts: PushAlertOpts = {},
): Promise<boolean> {
  if (!HCA_INTERNAL_KEY || !NEXT_APP_URL) return false;
  const { alertKey, url = '/', category, urgent, resendMinutes, deviceId } = opts;
  try {
    await fetch(`${NEXT_APP_URL}/api/push/notify`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-HCA-Internal-Key': HCA_INTERNAL_KEY,
      },
      body: JSON.stringify({
        title, body, url,
        ...(category ? { category } : {}),
        ...(alertKey ? { alertKey } : {}),
        ...(urgent ? { urgent: true } : {}),
        ...(resendMinutes ? { resendMinutes } : {}),
        ...(deviceId ? { deviceId } : {}),
      }),
      signal: AbortSignal.timeout(5_000),
    });
    return true;
  } catch (err) {
    console.warn('[push] notify failed:', err instanceof Error ? err.message : err);
    return false;
  }
}

/** Returns false when the app couldn't be reached. A dropped clear leaves the
 *  alert re-firing every 24 h forever, so the caller must keep it pending. */
async function clearPushAlert(alertKey: string): Promise<boolean> {
  if (!HCA_INTERNAL_KEY || !NEXT_APP_URL) return false;
  try {
    await fetch(`${NEXT_APP_URL}/api/push/notify`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-HCA-Internal-Key': HCA_INTERNAL_KEY,
      },
      body: JSON.stringify({ alertKey, clear: true }),
      signal: AbortSignal.timeout(5_000),
    });
    return true;
  } catch (err) {
    console.warn('[push] clear failed:', err instanceof Error ? err.message : err);
    return false;
  }
}

// One consolidated alert per sensor type, sent after each poll cycle.
const BATTERY_TYPES = [
  { class: 'motion-sensor',  alertKey: 'low-battery:motion', screen: 'motion', category: 'motion', label: 'motion sensor' },
  { class: 'leak-sensor',    alertKey: 'low-battery:leak',   screen: 'leak',   category: 'leak',   label: 'water leak sensor' },
  { class: 'contact-sensor', alertKey: 'low-battery:door',   screen: 'doors',  category: 'doors',  label: 'door sensor' },
] as const;

// In-memory map: alertKey → timestamp of last sendPushAlert call.
// Prevents hammering the notify endpoint every poll cycle.
// The notify endpoint's file-based record is the safety net on restart.
const alertSentAt = new Map<string, number>();
const ALERT_RESEND_MS = 24 * 60 * 60 * 1000;

// Which devices of a class have ever reported a battery state since startup, and
// how many that was on the previous cycle.
//
// Waiting for EVERY device of the class to confirm — the obvious rule — never
// completes: some sensors have no battery sub-node in the snapshot at all (two
// motion sensors and five contact sensors here), so their lowBattery stays
// undefined for ever and the alert can never clear. Tracking who has actually
// reported, and only judging once that set stops growing, gives the same
// protection against clearing on a half-filled snapshot without the deadlock.
const batteryReporters = new Map<string, Set<string>>();
const batteryReportersLastSize = new Map<string, number>();

// When each alert was last confirmed clear. The raise bookkeeping lives in this
// process, but the alert itself is persisted by the app — so an alert raised
// before a restart is invisible here, and gating the clear on our own map is how
// motion and leak ended up re-firing daily with nothing behind them. Instead the
// clear is idempotent and re-issued at this interval while the class is healthy.
const alertClearedAt = new Map<string, number>();
const CLEAR_RECHECK_MS = 60 * 60 * 1000;

// Alerts with a POST in flight. The send is only recorded once it lands, and the
// poll runs every second — without this, one 5 s timeout is five duplicate sends.
const alertInFlight = new Set<string>();

async function checkBatteryAlerts(): Promise<void> {
  const snap = getSnapshot() as Record<string, Record<string, unknown>>;
  const now = Date.now();
  for (const bt of BATTERY_TYPES) {
    // All device IDs of this class across all EISYs (from devices.json).
    const knownIds = Object.keys(devices).filter(id => devices[id]?.class === bt.class);
    if (knownIds.length === 0) continue;

    const lowCount = knownIds.filter(id => snap[id]?.lowBattery === true).length;

    let reporters = batteryReporters.get(bt.class);
    if (!reporters) { reporters = new Set(); batteryReporters.set(bt.class, reporters); }
    for (const id of knownIds) {
      if (snap[id]?.lowBattery !== undefined) reporters.add(id);
    }
    const settled = reporters.size > 0 && reporters.size === batteryReportersLastSize.get(bt.class);
    batteryReportersLastSize.set(bt.class, reporters.size);

    if (lowCount > 0) {
      // Only call the API on first detection or after 24h — not every poll cycle.
      const lastSent = alertSentAt.get(bt.alertKey);
      const dueToSend = lastSent === undefined || now - lastSent >= ALERT_RESEND_MS;
      if (dueToSend && !alertInFlight.has(bt.alertKey)) {
        alertInFlight.add(bt.alertKey);
        const noun = bt.label + (lowCount > 1 ? 's' : '');
        const verb = lowCount > 1 ? 'need' : 'needs';
        // Only record the send once it has actually left, so a failed POST is
        // retried next cycle instead of muting the alert for a day.
        void sendPushAlert(
          'Low Battery',
          `${lowCount} ${noun} ${verb} a new battery.`,
          { alertKey: bt.alertKey, url: `/?screen=${bt.screen}`, category: bt.category },
        ).then(sent => {
          alertInFlight.delete(bt.alertKey);
          if (!sent) return;
          alertSentAt.set(bt.alertKey, now);
          alertClearedAt.delete(bt.alertKey);
        });
      }
    } else if (settled) {
      // Keep the raise on record until the clear lands — a dropped one would
      // leave the app re-sending this alert daily with nothing behind it.
      const lastClear = alertClearedAt.get(bt.alertKey);
      const due = alertSentAt.has(bt.alertKey)
        || lastClear === undefined
        || now - lastClear >= CLEAR_RECHECK_MS;
      if (due && !alertInFlight.has(bt.alertKey)) {
        alertInFlight.add(bt.alertKey);
        void clearPushAlert(bt.alertKey).then(cleared => {
          alertInFlight.delete(bt.alertKey);
          if (!cleared) return;
          alertSentAt.delete(bt.alertKey);
          alertClearedAt.set(bt.alertKey, now);
        });
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Water leak alerts
//
// Unlike a low battery, a leak is doing damage while it goes unanswered, so it
// alerts per sensor (the room matters), at high urgency, and repeats every
// 30 minutes until the sensor reports dry. The app clears the alert and its
// home-screen banner off the same dry reading — there is nothing to dismiss.
// ---------------------------------------------------------------------------

const LEAK_RESEND_MS = 30 * 60 * 1000;

async function checkLeakAlerts(): Promise<void> {
  const snap = getSnapshot() as Record<string, Record<string, unknown>>;
  const now = Date.now();

  for (const id of Object.keys(devices)) {
    if (devices[id]?.class !== 'leak-sensor') continue;
    const alertKey = `leak:${id}`;
    const wet = snap[id]?.wet;

    if (wet === true) {
      const lastSent = alertSentAt.get(alertKey);
      if (lastSent === undefined || now - lastSent >= LEAK_RESEND_MS) {
        alertSentAt.set(alertKey, now);
        void sendPushAlert('Water Leak Detected', 'Water detected by {device}.', {
          alertKey,
          deviceId: id,
          url: '/?screen=leak',
          category: 'leak',
          urgent: true,
          resendMinutes: LEAK_RESEND_MS / 60_000,
        });
      }
    } else if (wet === false && alertSentAt.has(alertKey)) {
      // Only on a confirmed dry reading — `undefined` means we haven't polled this
      // sensor yet, and a leak must never be cleared by absence of information.
      alertSentAt.delete(alertKey);
      void clearPushAlert(alertKey);
    }
  }
}

// ---------------------------------------------------------------------------
// TV variables ⇄ Harmony hubs
//
// `_House_TV_<Room>_On` is how the rest of the house learns that a TV went on or
// off — the room's lighting EISY gets it mirrored over a network resource, and
// its programs work off that. The app used to write it, and does not any more:
// power goes straight to the hub now, because the variable could not see a TV
// turned on by hand and nothing guaranteed anything acted on a write to it.
//
// That leaves the variable with only the EISY's own `TV <Room> Harmony - On/Off`
// programs behind it — sixteen of them, whose bodies aren't visible from here,
// one per room per direction. Rather than trust all sixteen, converge the
// variable on the hub we already poll every second. The variable stops being a
// parallel belief about the room and becomes a restatement of the hub's own
// answer, for every room at once.
//
// Writes go out only on a genuine disagreement, and only once the variable has
// actually been read this run — never on the absence of information.
// ---------------------------------------------------------------------------

/** Hub state id → the value we last asked its variable to take, and when.
 *  The EISY needs a poll cycle or two to report the write back; without this the
 *  same command would be re-sent every second until it did. */
const tvVarWrites = new Map<string, { want: boolean; at: number }>();

/** How long to let a write settle before re-asserting it. Long enough to cover a
 *  slow EISY, short enough that a genuinely lost write is retried. */
const TV_VAR_SETTLE_MS = 15_000;

async function syncTvVariables(): Promise<void> {
  const snap = getSnapshot() as Record<string, Record<string, unknown> | undefined>;
  const now = Date.now();

  for (const [hubId, entry] of Object.entries(devices)) {
    if (entry.class !== 'harmony-hub' || !entry.tvVarStateId) continue;

    const hubOn = snap[hubId]?.on;
    if (typeof hubOn !== 'boolean') continue; // hub not polled yet

    const varEntry = devices[entry.tvVarStateId];
    if (!varEntry || varEntry.varType == null || varEntry.varId == null) continue;

    // A variable we have never read is not a variable we know disagrees.
    const varOn = snap[entry.tvVarStateId]?.on;
    if (typeof varOn !== 'boolean') continue;

    if (varOn === hubOn) { tvVarWrites.delete(hubId); continue; }

    const pending = tvVarWrites.get(hubId);
    if (pending && pending.want === hubOn && now - pending.at < TV_VAR_SETTLE_MS) continue;

    tvVarWrites.set(hubId, { want: hubOn, at: now });
    const baseUrl = EISY_URLS[varEntry.eisyIdx];
    try {
      console.log(
        `[tv-var] ${entry.name ?? hubId} is ${hubOn ? 'on' : 'off'} — setting ${entry.tvVarStateId} to ${hubOn ? 1 : 0}`,
      );
      await setVariable(baseUrl, varEntry.varType, varEntry.varId, hubOn ? 1 : 0);
    } catch (err) {
      // Clear the record so the next cycle retries rather than waiting out the
      // settle window on a write that never left.
      tvVarWrites.delete(hubId);
      console.warn(`[tv-var] ${entry.tvVarStateId} FAILED:`, err instanceof Error ? err.message : err);
    }
  }
}

// ---------------------------------------------------------------------------
// Polling loop
// ---------------------------------------------------------------------------

async function pollEisy(eisyIdx: number): Promise<void> {
  const baseUrl = EISY_URLS[eisyIdx];

  // Nodes (Insteon devices)
  const nodeStatus = await getNodeStatus(baseUrl);
  for (const [address, props] of nodeStatus) {
    const stateId = `eisy${eisyIdx}/${address}`;
    const entry = devices[stateId];
    if (!entry) continue;
    // Contact sensor battery (2845-222 sub-node 4): ST > 0 = low battery.
    // Patch lowBattery directly onto the linked variable state (the contact-sensor's stateId).
    if (entry.class === 'contact-battery') {
      const isLow = (props.get('ST') ?? 0) > 0;
      if (entry.linkedStateId) applyPatch(entry.linkedStateId, { lowBattery: isLow });
      continue;
    }

    const state = nodeToState(entry.class, props);
    // Leak sensors: node 1 = Dry, node 2 = Wet, node 4 = Heartbeat.
    // Read wet state from node 2 (overriding the dry-node value).
    // Battery: absence of heartbeat (node 4 ST === 0) means low battery.
    // State is emitted under the node-1 key so the WP controlStateIds mapping stays valid.
    if (entry.class === 'leak-sensor' && address.endsWith(' 1')) {
      const wetAddr  = address.slice(0, -1) + '2';
      const battAddr = address.slice(0, -1) + '4';
      const wetProps  = nodeStatus.get(wetAddr);
      (state as Record<string, unknown>).wet = (wetProps?.get('ST') ?? 0) > 0;
      if (devices[`eisy${eisyIdx}/${battAddr}`]?.class === 'leak-battery') {
        const battProps = nodeStatus.get(battAddr);
        const isLow = (battProps?.get('ST') ?? 0) === 0; // no heartbeat = low battery
        (state as Record<string, unknown>).lowBattery = isLow;
      } else {
        // Explicitly clear so stale values from previous runs don't persist.
        (state as Record<string, unknown>).lowBattery = false;
      }
    }
    // Motion sensors: node 1 = motion, node 2 = dawn/dusk, node 3 = battery.
    if (entry.class === 'motion-sensor' && address.endsWith(' 1')) {
      const battAddr = address.slice(0, -1) + '3';
      if (devices[`eisy${eisyIdx}/${battAddr}`]?.class === 'motion-battery') {
        const battProps = nodeStatus.get(battAddr);
        const isLow = (battProps?.get('ST') ?? 0) > 0;
        (state as Record<string, unknown>).lowBattery = isLow;
      } else {
        (state as Record<string, unknown>).lowBattery = false;
      }
    }
    applyPatch(stateId, state);
  }

  // Integer variables (type 1) + state variables (type 2)
  for (const varType of [1, 2] as const) {
    const vars = await getVariables(baseUrl, varType);
    for (const [varId, val] of vars) {
      const stateId = `eisy${eisyIdx}/var/${varId}`;
      const entry = devices[stateId];
      if (!entry) continue;
      // Only apply if this entry's stored varType matches (avoids type-1/type-2 collisions)
      if (entry.varType !== undefined && entry.varType !== varType) continue;
      applyPatch(stateId, varToState(entry.class, val));
    }
  }
}

async function pollAll(): Promise<void> {
  await Promise.allSettled(
    EISY_URLS.map((_, idx) =>
      pollEisy(idx).catch((err: unknown) =>
        console.warn(`[eisy${idx}] poll error:`, err instanceof Error ? err.message : err),
      ),
    ),
  );
}

// Non-overlapping poll loop — waits for each poll to finish before
// scheduling the next. Prevents connection exhaustion when polls are
// slower than POLL_MS (e.g. under network hiccups or high EISY load).
(async function pollLoop() {
  while (true) {
    const t0 = Date.now();
    await pollAll();
    void syncTvVariables().catch((err: unknown) =>
      console.warn('[tv-var] sync error:', err instanceof Error ? err.message : err),
    );
    void checkBatteryAlerts();
    void checkLeakAlerts();
    const wait = Math.max(0, POLL_MS - (Date.now() - t0));
    if (wait > 0) await new Promise<void>(r => setTimeout(r, wait));
  }
})().catch(console.error);

// ---------------------------------------------------------------------------
// Express app
// ---------------------------------------------------------------------------

const app = express();
app.use(cors());
app.use(express.json());

// GET /state — full snapshot
app.get('/state', (_req: Request, res: Response) => {
  res.json(getSnapshot());
});

// GET /stream — SSE
const SSE_HEADERS = {
  'Content-Type':      'text/event-stream',
  'Cache-Control':     'no-cache, no-transform',
  'Connection':        'keep-alive',
  'X-Accel-Buffering': 'no',
} as const;

app.get('/stream', (req: Request, res: Response) => {
  res.writeHead(200, SSE_HEADERS);
  res.write(': connected\n\n');

  const unsub = subscribe((chunk) => {
    res.write(chunk);
    (res as unknown as { flush?: () => void }).flush?.();
  });

  // A real event, not a `:` comment: EventSource never surfaces comments to JS,
  // so a comment keeps the socket warm but tells the client nothing. The client
  // uses this to tell "quiet house" apart from "connection died while the phone
  // was asleep", which is invisible from readyState alone.
  const heartbeat = setInterval(() => {
    try { res.write('event: ping\ndata: {}\n\n'); }
    catch { clearInterval(heartbeat); }
  }, 30_000);

  req.on('close', () => {
    unsub();
    clearInterval(heartbeat);
  });
});

// POST /command
interface CommandBody {
  target: string;
  patch?: Record<string, unknown>;
  action?: string;
}

app.post('/command', (req: Request, res: Response) => {
  const body = req.body as CommandBody;
  if (!body?.target) {
    res.status(400).json({ error: 'Missing target' });
    return;
  }

  const entry = devices[body.target];
  if (!entry) {
    // Unknown target — log and return 404.
    // (Scenes and non-device targets pass through without a devices.json entry.)
    console.warn(`[command] unknown target: ${body.target}`);
    res.status(404).json({ error: `Unknown target: ${body.target}` });
    return;
  }

  // Respond 202 immediately (optimistic model — stream confirms)
  res.status(202).end();

  // NOTE: We deliberately do NOT apply the patch optimistically here.
  // The client already applied it locally (optimistic UI) and holds a command lock
  // that suppresses intermediate SSE values. Fanning the optimistic patch out on SSE
  // prematurely releases the client lock — before the EISY has confirmed — letting
  // the next poll (with the old device value) overwrite the UI. The confirmed state
  // arrives on its own within the next poll cycle.

  // Forward to EISY asynchronously
  const baseUrl = EISY_URLS[entry.eisyIdx];
  void (async () => {
    try {
      if (body.action === 'query' && entry.type === 'device' && entry.address) {
        // Force the EISY to re-read the physical device via ST command.
        // Useful for motion sensors: clears stale lowBattery state without a manual reboot.
        console.log(`[command] query ${body.target} → ${baseUrl} ST`);
        await sendNodeCommand(baseUrl, entry.address, 'ST');
        if (entry.class === 'motion-sensor' && entry.address.endsWith(' 1')) {
          const battAddr = entry.address.slice(0, -1) + '3';
          await sendNodeCommand(baseUrl, battAddr, 'ST');
        }
        console.log(`[command] query ${body.target} ✓`);
      } else if (entry.type === 'device' && entry.address) {
        const nodeCmd = patchToNodeCommand(entry.class, body.patch ?? {}, body.action);
        if (nodeCmd) {
          console.log(`[command] node ${body.target} → ${baseUrl} ${nodeCmd.cmd}${nodeCmd.value !== undefined ? '/' + nodeCmd.value : ''}`);
          await sendNodeCommand(baseUrl, entry.address, nodeCmd.cmd, nodeCmd.value);
        }
      } else if (entry.type === 'variable' && entry.varType != null && entry.varId != null) {
        // Accept any boolean state field (on/open/locked → 1/0) or an explicit
        // numeric value. Matches the per-class shapes varToState emits, so e.g.
        // a contact-sensor door sends { open } and a flag sends { on }.
        const boolField = body.patch?.on ?? body.patch?.open ?? body.patch?.locked;
        const val = typeof boolField === 'boolean'
          ? (boolField ? 1 : 0)
          : typeof body.patch?.value === 'number'
            ? Math.round(body.patch.value as number)
            : 0;
        console.log(`[command] var ${body.target} → ${baseUrl} vars/set/${entry.varType}/${entry.varId}/${val}`);
        await setVariable(baseUrl, entry.varType, entry.varId, val);
        console.log(`[command] var ${body.target} ✓`);
      }
    } catch (err) {
      console.warn(
        `[command] ${body.target} FAILED:`,
        err instanceof Error ? err.message : err,
      );
    }
  })();
});

app.listen(PORT, () => {
  console.log(`home-control-service listening on :${PORT}`);
  console.log(`  /state   GET  full snapshot`);
  console.log(`  /stream  GET  SSE patch stream`);
  console.log(`  /command POST device commands`);
});
