// =============================================================================
// Auth utilities — Home Control App
//
// Uses the Web Crypto API (crypto.subtle) so this module runs in both
// the Next.js Edge runtime (middleware) and Node.js API routes.
//
// WP generates a short-lived HMAC token using WP's own AUTH_KEY and embeds
// it as a meta tag in the PHP-rendered app shell. The React app exchanges it
// for a Next.js session cookie via POST /api/auth/exchange. The middleware
// validates the session cookie on all protected API routes.
//
// Token formats (stateless, no DB writes):
//   WP init token:  "<userId>.<hex_hmac_sha256(userId|hour, WP_AUTH_KEY)>"
//   Session cookie: "<userId>|<expiry_ts>.<hex_hmac_sha256(payload, NEXTAUTH_SECRET)>"
// =============================================================================

const SESSION_MAX_AGE = 8 * 60 * 60; // 8 hours in seconds

// ---------------------------------------------------------------------------
// Internal Web Crypto helpers
// ---------------------------------------------------------------------------

async function importKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign', 'verify'],
  );
}

async function hmacHex(secret: string, message: string): Promise<string> {
  const key = await importKey(secret);
  const sig = await crypto.subtle.sign(
    'HMAC',
    key,
    new TextEncoder().encode(message),
  );
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

async function hmacVerify(
  secret: string,
  message: string,
  hexSig: string,
): Promise<boolean> {
  if (hexSig.length % 2 !== 0) return false;
  const key = await importKey(secret);
  const sigBytes = new Uint8Array(
    (hexSig.match(/.{2}/g) ?? []).map((b) => parseInt(b, 16)),
  );
  try {
    return await crypto.subtle.verify(
      'HMAC',
      key,
      sigBytes,
      new TextEncoder().encode(message),
    );
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// WP HMAC token (one-time exchange token generated by PHP)
// ---------------------------------------------------------------------------

/**
 * Verify a WP-generated HMAC token.
 * Accepts tokens from the current hour and the previous hour (~2h window).
 * Returns the userId on success, null on failure.
 */
export async function verifyWpToken(token: string): Promise<number | null> {
  const key = process.env.WP_AUTH_KEY;
  if (!key) throw new Error('WP_AUTH_KEY env var is not set');

  const dot = token.indexOf('.');
  if (dot < 1) return null;

  const userId = parseInt(token.slice(0, dot), 10);
  const sig = token.slice(dot + 1);
  if (!userId || !sig) return null;

  const now = Math.floor(Date.now() / 1000 / 3600);
  for (const offset of [0, 1]) {
    const ok = await hmacVerify(key, `${userId}|${now - offset}`, sig);
    if (ok) return userId;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Next.js session cookie
// ---------------------------------------------------------------------------

function getSessionKey(): string {
  const key = process.env.NEXTAUTH_SECRET;
  if (!key) throw new Error('NEXTAUTH_SECRET env var is not set');
  return key;
}

/** Sign a session string for the given userId. Valid for SESSION_MAX_AGE seconds. */
export async function signSession(userId: number): Promise<string> {
  const expiry = Math.floor(Date.now() / 1000) + SESSION_MAX_AGE;
  const payload = `${userId}|${expiry}`;
  const sig = await hmacHex(getSessionKey(), payload);
  return `${payload}.${sig}`;
}

/**
 * Verify a session cookie value.
 * Returns the userId on success, null if missing, malformed, expired, or tampered.
 */
export async function verifySession(session: string): Promise<number | null> {
  const dot = session.lastIndexOf('.');
  if (dot < 1) return null;

  const payload = session.slice(0, dot);
  const sig = session.slice(dot + 1);

  const ok = await hmacVerify(getSessionKey(), payload, sig);
  if (!ok) return null;

  const [userIdStr, expiryStr] = payload.split('|');
  const userId = parseInt(userIdStr, 10);
  const expiry = parseInt(expiryStr, 10);

  if (!userId || !expiry) return null;
  if (Math.floor(Date.now() / 1000) > expiry) return null;

  return userId;
}

// ---------------------------------------------------------------------------
// Client-side helper (DOM only)
// ---------------------------------------------------------------------------

/** Read the one-time WP init token from the meta tag in the page. */
export function readInitToken(): string {
  if (typeof document === 'undefined') return '';
  return (
    document
      .querySelector<HTMLMetaElement>('meta[name="hca-init-token"]')
      ?.content ?? ''
  );
}
