// =============================================================================
// Auth utilities — Home Control App
//
// Uses the Web Crypto API (crypto.subtle) so this module runs in both
// the Next.js Edge runtime (middleware) and Node.js API routes.
//
// WP generates a short-lived HMAC token using WP's own AUTH_KEY and embeds
// it as a meta tag in the PHP-rendered app shell. The React app exchanges it
// for a Next.js session cookie via POST /api/auth/exchange. The middleware
// validates the session cookie on all protected API routes.
//
// Token formats (stateless, no DB writes):
//   WP init token:  "<userId>.<hex_hmac_sha256(userId|hour, WP_AUTH_KEY)>"
//   Session cookie: "<userId>|<expiry_ts>|<issued_ts>.<hex_hmac_sha256(payload, NEXTAUTH_SECRET)>"
// =============================================================================

/**
 * How long a session lives without being renewed.
 *
 * This is a house control panel on the owner's own phone, reached over the home
 * network — the thing it protects is a light switch, and the cost of a short
 * session is being thrown out to a login screen mid-use. The middleware slides
 * the expiry on every authenticated request (see SESSION_RENEW_AFTER), so this
 * is really "how long the app may sit unopened before asking again".
 */
export const SESSION_MAX_AGE = 30 * 24 * 60 * 60; // 30 days

/** Re-issue the cookie once a session is past halfway through its life. Anyone
 *  using the app at all stays signed in; the renewal costs one HMAC. */
export const SESSION_RENEW_AFTER = SESSION_MAX_AGE / 2;

export const SESSION_COOKIE = 'hca_session';

/** One definition of the cookie, so the four places that set it can't drift. */
export const sessionCookieOptions = {
  httpOnly: true,
  sameSite: 'lax' as const, // lax (not strict) so the WP login redirect lands with the cookie intact
  path: '/',
  maxAge: SESSION_MAX_AGE,
};

// ---------------------------------------------------------------------------
// Internal Web Crypto helpers
// ---------------------------------------------------------------------------

async function importKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign', 'verify'],
  );
}

async function hmacHex(secret: string, message: string): Promise<string> {
  const key = await importKey(secret);
  const sig = await crypto.subtle.sign(
    'HMAC',
    key,
    new TextEncoder().encode(message),
  );
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

async function hmacVerify(
  secret: string,
  message: string,
  hexSig: string,
): Promise<boolean> {
  if (hexSig.length % 2 !== 0) return false;
  const key = await importKey(secret);
  const sigBytes = new Uint8Array(
    (hexSig.match(/.{2}/g) ?? []).map((b) => parseInt(b, 16)),
  );
  try {
    return await crypto.subtle.verify(
      'HMAC',
      key,
      sigBytes,
      new TextEncoder().encode(message),
    );
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// WP HMAC token (one-time exchange token generated by PHP)
// ---------------------------------------------------------------------------

/**
 * Verify a WP-generated HMAC token.
 * Accepts tokens from the current hour and the previous hour (~2h window).
 * Returns the userId on success, null on failure.
 */
export async function verifyWpToken(token: string): Promise<number | null> {
  const key = process.env.WP_AUTH_KEY;
  if (!key) throw new Error('WP_AUTH_KEY env var is not set');

  const dot = token.indexOf('.');
  if (dot < 1) return null;

  const userId = parseInt(token.slice(0, dot), 10);
  const sig = token.slice(dot + 1);
  if (!userId || !sig) return null;

  const now = Math.floor(Date.now() / 1000 / 3600);
  for (const offset of [0, 1]) {
    const ok = await hmacVerify(key, `${userId}|${now - offset}`, sig);
    if (ok) return userId;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Next.js session cookie
// ---------------------------------------------------------------------------

function getSessionKey(): string {
  const key = process.env.NEXTAUTH_SECRET;
  if (!key) throw new Error('NEXTAUTH_SECRET env var is not set');
  return key;
}

/** Sign a session string for the given userId. Valid for SESSION_MAX_AGE seconds.
 *  The issued-at is what lets WP revoke a session it never saw: an epoch bump
 *  rejects everything signed before it. */
export async function signSession(userId: number): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  const payload = `${userId}|${now + SESSION_MAX_AGE}|${now}`;
  const sig = await hmacHex(getSessionKey(), payload);
  return `${payload}.${sig}`;
}

/**
 * Verify a session cookie value.
 * Returns the userId and its expiry, or null if missing, malformed, expired or
 * tampered with. The expiry is what lets the middleware slide the session.
 */
export async function readSession(
  session: string,
): Promise<{ userId: number; expiry: number; issuedAt: number } | null> {
  const dot = session.lastIndexOf('.');
  if (dot < 1) return null;

  const payload = session.slice(0, dot);
  const sig = session.slice(dot + 1);

  const ok = await hmacVerify(getSessionKey(), payload, sig);
  if (!ok) return null;

  const [userIdStr, expiryStr, issuedStr] = payload.split('|');
  const userId = parseInt(userIdStr, 10);
  const expiry = parseInt(expiryStr, 10);
  // Cookies signed before the issued-at existed read as 0, which any revocation
  // outranks — the safe direction for a field that used to be absent.
  const issuedAt = parseInt(issuedStr ?? '', 10) || 0;

  if (!userId || !expiry) return null;
  if (Math.floor(Date.now() / 1000) > expiry) return null;

  return { userId, expiry, issuedAt };
}

/**
 * Verify a session cookie value.
 * Returns the userId on success, null if missing, malformed, expired, or tampered.
 */
export async function verifySession(session: string): Promise<number | null> {
  return (await readSession(session))?.userId ?? null;
}

// ---------------------------------------------------------------------------
// Client-side helper (DOM only)
// ---------------------------------------------------------------------------

/** Read the one-time WP init token from the meta tag in the page. */
export function readInitToken(): string {
  if (typeof document === 'undefined') return '';
  return (
    document
      .querySelector<HTMLMetaElement>('meta[name="hca-init-token"]')
      ?.content ?? ''
  );
}

/**
 * Dispatch a 'hca:session-expired' event on window.
 * Called by the state client when any protected API responds with 401.
 * AuthGate listens for this and shows the re-auth dialog without a page reload.
 */
export function dispatchSessionExpired(): void {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('hca:session-expired'));
  }
}
